In [1]:
import json
import pandas as pd

valid_records = []
invalid_record_count = 0

with open("results/20260812_202653.records.jsonl", "r") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
            
        try:
            valid_records.append(json.loads(line))
        except json.JSONDecodeError:
            invalid_record_count += 1
            # Skip the corrupted line (usually the very last one where you killed the script)
            pass

# pd.json_normalize automatically flattens nested dictionaries.
# A JSON structure like {"result": {"score": 0.8}} becomes a column named "result.score"
df = pd.json_normalize(valid_records)

print(f"Loaded {len(df)}/{len(df) + invalid_record_count} valid records.")

Loaded 181/181 valid records.

In [2]:
df.columns

Index(['setting.prompt.setting.system_prompt',
       'setting.prompt.setting.response_format.type',
       'setting.prompt.setting.prompt_format', 'setting.prompt.name',
       'setting.model', 'input.text', 'input.language.source_language',
       'input.language.target_language', 'result.translation', 'result.rating',
       'metadata.created_at', 'metadata.success', 'metadata.error',
       'metadata.elapsed_seconds'],
      dtype='str')

In [3]:
df['setting.model']

0      qwen3-8b
1      qwen3-8b
2      qwen3-8b
3      qwen3-8b
4      qwen3-8b
         ...
176    qwen3-8b
177    qwen3-8b
178    qwen3-8b
179    qwen3-8b
180    qwen3-8b
Name: setting.model, Length: 181, dtype: str

In [5]:
pd.set_option('display.max_colwidth', 60)
df[["input.text", "result.translation", "result.rating", "setting.model", "setting.prompt.name"]].sort_values("result.rating")

,input.text,result.translation,result.rating,setting.model,setting.prompt.name
29,Those who practise magical arts of blowing on knots-the ...,Yang mempraktikkan seni magis menghembuskan napas ke sim...,-0.621145,qwen3-8b,verbose
27,Those who practise magical arts of blowing on knots-the ...,Orang-orang yang mempraktikkan ilmu sihir menghembuskan ...,-0.529700,qwen3-8b,minimal
28,Those who practise magical arts of blowing on knots-the ...,Yang mempraktikkan seni magis meniup simpul-simpul - sih...,-0.369753,qwen3-8b,professional
58,An angel got her strangled by the very rope she used to ...,Seorang malaikat menggantungkan tali yang sama yang digu...,-0.338347,qwen3-8b,professional
141,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered l...","'_Asfin Makool'_ , yaitu, rumput yang telah dimakan, yai...",-0.329658,qwen3-8b,minimal
...,...,...,...,...,...
72,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
78,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
52,When Abu-Lahab will be in the hell-fire and then he woul...,"Ketika Abu-Lahab berada di api neraka, nanti dia akan me...",0.387317,qwen3-8b,professional
63,"See <{[""Q"", ""110:1""]}>","Lihat <{[""Q"", ""110:1""]}>",0.415419,qwen3-8b,minimal
64,"See <{[""Q"", ""110:1""]}>","Lihat <{[""Q"", ""110:1""]}>",0.415419,qwen3-8b,professional

In [8]:
display(df.groupby(['setting.prompt.name', 'setting.model'])['metadata.elapsed_seconds'].describe())
display(df.groupby(['setting.prompt.name', 'setting.model'])['result.rating'].describe())

,,count,mean,std,min,25%,50%,75%,max
setting.prompt.name,setting.model,,,,,,,,
minimal,qwen3-8b,61.0,6.644854,5.328131,2.798317,3.351026,4.327142,7.881365,31.159906
professional,qwen3-8b,60.0,6.586182,5.298610,2.815771,3.326645,4.284510,8.161167,31.186950
verbose,qwen3-8b,60.0,6.789303,5.433011,2.788934,3.368427,4.369940,7.904989,31.706455

,,count,mean,std,min,25%,50%,75%,max
setting.prompt.name,setting.model,,,,,,,,
minimal,qwen3-8b,61.0,0.071637,0.220833,-0.529700,-0.093439,0.052275,0.253908,0.415419
professional,qwen3-8b,60.0,0.055823,0.225369,-0.369753,-0.129028,0.053291,0.234320,0.415419
verbose,qwen3-8b,60.0,-0.001923,0.189815,-0.621145,-0.133392,0.012901,0.133496,0.374963

In [9]:
val = df['input.text'].values
val

[v for v in val if any(k in v for k in '<{[(')]

['Be the evil doers, the Jinns or human beings. It is a well-known fact that among the forces hidden from the human eye, which are active in the world, there are good and also bad ones among them. Jinns, like Satan are spiritual beings<{["F", 1]}>.\n\n**The End**',
 'Be the evil doers, the Jinns or human beings. It is a well-known fact that among the forces hidden from the human eye, which are active in the world, there are good and also bad ones among them. Jinns, like Satan are spiritual beings<{["F", 1]}>.\n\n**The End**',
 'Be the evil doers, the Jinns or human beings. It is a well-known fact that among the forces hidden from the human eye, which are active in the world, there are good and also bad ones among them. Jinns, like Satan are spiritual beings<{["F", 1]}>.\n\n**The End**',
 "'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).",
 "'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).",
 "'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).",
 "'_Ghasiq'_ or intense darkness - The miserable difficulties and calamities which can also be compared to darkness against the jovial case in prosperity which can be compared to light (Difficulties include physical, mental and spiritual).",
 "'_Ghasiq'_ or intense darkness - The miserable difficulties and calamities which can also be compared to darkness against the jovial case in prosperity which can be compared to light (Difficulties include physical, mental and spiritual).",
 "'_Ghasiq'_ or intense darkness - The miserable difficulties and calamities which can also be compared to darkness against the jovial case in prosperity which can be compared to light (Difficulties include physical, mental and spiritual).",
 'The Jews asked the Holy Prophet to describe the identity or to relate the genealogy of God and the Messenger Angel brought this Surah.\n\nThere is a vast difference between the two Arabic words \'\'_Ahad\'_ and \'_Wahid\'_ both commonly thought to mean Oneness. To indicate the Unity of God, it is said in this verse that God is \'_Ahad\'_ i.e., One, One in the sense of the Absolute Oneness of His Essential Existence, not in the numerical sense of the numeral which has its second and third but the One which has no second of it. The expression one, is in the sense of being the ONLY in conceiving Whose existence all the faculties of the human intellect are helpless. He is such a one that even His attributes are His Essence and not separate and never separable from Him. It is a death-blow, Islam rendered to all imaginary conception of any kind of polytheistic doctrines and the phenomena of plurality about the All-Divine<{["F", 1]}>. He is One with none comparable to Him, without any beginning or end, Unlimited by time, space or circumstances. A reality before which all others have no existence. He is the Creator, One and everything is His creation.\n\nThis chapter with all its brevity is considered to contain the gist or the spirit of the Absolute Unity of God which is the fundamental of the fundamentals of the faith, Islam. It is considered that one third of Qur\'an is revealed as an explanation to this Synthesis. It is said that the Holy Prophet was asked to give the idea of Godhead which he preached, and this Chapter was revealed.\n\nIt begins with pronoun - third person - Singular - Ar. \'_Hu\'_, i.e., He which refers to something- known to all but not identified with any, as against the usual reference in the term of first-person singular \'I\' of the conception of the Absolute in the Aryan creeds - saying the \'_Athma\'_ and the \'_Brahma\'_ both are one. For the word Refer to: <{["Q", "1:1"]}> - \'_Ahad\'_ stands for Unity of His Essence, i.e., He is not of composite nature. \'_Samad\'_ stands to denote that He is all-compact in His Unity in the sense that He cannot be described or defined to be void of any excellence or any excellence to be void of Him. Thus, He is all in all in the true sense of the term discarding every possibility of incarnation. Thus proves His all-pervadingness and all-comprehensiveness which means His being infinite - as such the question of His being in the sense of something separated from Him as his issue or His being separated from anybody from any origin, i.e., His being born - does not at all arise - and it is self- evident that there cannot be a second or a match or a rival for such a being. It is unimaginable because the very idea of the existence of two, implies the finiteness and the limitation of both which is contradictory to the very idea of the Absolute unity of the Essence. (A.P.).',
 'The Jews asked the Holy Prophet to describe the identity or to relate the genealogy of God and the Messenger Angel brought this Surah.\n\nThere is a vast difference between the two Arabic words \'\'_Ahad\'_ and \'_Wahid\'_ both commonly thought to mean Oneness. To indicate the Unity of God, it is said in this verse that God is \'_Ahad\'_ i.e., One, One in the sense of the Absolute Oneness of His Essential Existence, not in the numerical sense of the numeral which has its second and third but the One which has no second of it. The expression one, is in the sense of being the ONLY in conceiving Whose existence all the faculties of the human intellect are helpless. He is such a one that even His attributes are His Essence and not separate and never separable from Him. It is a death-blow, Islam rendered to all imaginary conception of any kind of polytheistic doctrines and the phenomena of plurality about the All-Divine<{["F", 1]}>. He is One with none comparable to Him, without any beginning or end, Unlimited by time, space or circumstances. A reality before which all others have no existence. He is the Creator, One and everything is His creation.\n\nThis chapter with all its brevity is considered to contain the gist or the spirit of the Absolute Unity of God which is the fundamental of the fundamentals of the faith, Islam. It is considered that one third of Qur\'an is revealed as an explanation to this Synthesis. It is said that the Holy Prophet was asked to give the idea of Godhead which he preached, and this Chapter was revealed.\n\nIt begins with pronoun - third person - Singular - Ar. \'_Hu\'_, i.e., He which refers to something- known to all but not identified with any, as against the usual reference in the term of first-person singular \'I\' of the conception of the Absolute in the Aryan creeds - saying the \'_Athma\'_ and the \'_Brahma\'_ both are one. For the word Refer to: <{["Q", "1:1"]}> - \'_Ahad\'_ stands for Unity of His Essence, i.e., He is not of composite nature. \'_Samad\'_ stands to denote that He is all-compact in His Unity in the sense that He cannot be described or defined to be void of any excellence or any excellence to be void of Him. Thus, He is all in all in the true sense of the term discarding every possibility of incarnation. Thus proves His all-pervadingness and all-comprehensiveness which means His being infinite - as such the question of His being in the sense of something separated from Him as his issue or His being separated from anybody from any origin, i.e., His being born - does not at all arise - and it is self- evident that there cannot be a second or a match or a rival for such a being. It is unimaginable because the very idea of the existence of two, implies the finiteness and the limitation of both which is contradictory to the very idea of the Absolute unity of the Essence. (A.P.).',
 'The Jews asked the Holy Prophet to describe the identity or to relate the genealogy of God and the Messenger Angel brought this Surah.\n\nThere is a vast difference between the two Arabic words \'\'_Ahad\'_ and \'_Wahid\'_ both commonly thought to mean Oneness. To indicate the Unity of God, it is said in this verse that God is \'_Ahad\'_ i.e., One, One in the sense of the Absolute Oneness of His Essential Existence, not in the numerical sense of the numeral which has its second and third but the One which has no second of it. The expression one, is in the sense of being the ONLY in conceiving Whose existence all the faculties of the human intellect are helpless. He is such a one that even His attributes are His Essence and not separate and never separable from Him. It is a death-blow, Islam rendered to all imaginary conception of any kind of polytheistic doctrines and the phenomena of plurality about the All-Divine<{["F", 1]}>. He is One with none comparable to Him, without any beginning or end, Unlimited by time, space or circumstances. A reality before which all others have no existence. He is the Creator, One and everything is His creation.\n\nThis chapter with all its brevity is considered to contain the gist or the spirit of the Absolute Unity of God which is the fundamental of the fundamentals of the faith, Islam. It is considered that one third of Qur\'an is revealed as an explanation to this Synthesis. It is said that the Holy Prophet was asked to give the idea of Godhead which he preached, and this Chapter was revealed.\n\nIt begins with pronoun - third person - Singular - Ar. \'_Hu\'_, i.e., He which refers to something- known to all but not identified with any, as against the usual reference in the term of first-person singular \'I\' of the conception of the Absolute in the Aryan creeds - saying the \'_Athma\'_ and the \'_Brahma\'_ both are one. For the word Refer to: <{["Q", "1:1"]}> - \'_Ahad\'_ stands for Unity of His Essence, i.e., He is not of composite nature. \'_Samad\'_ stands to denote that He is all-compact in His Unity in the sense that He cannot be described or defined to be void of any excellence or any excellence to be void of Him. Thus, He is all in all in the true sense of the term discarding every possibility of incarnation. Thus proves His all-pervadingness and all-comprehensiveness which means His being infinite - as such the question of His being in the sense of something separated from Him as his issue or His being separated from anybody from any origin, i.e., His being born - does not at all arise - and it is self- evident that there cannot be a second or a match or a rival for such a being. It is unimaginable because the very idea of the existence of two, implies the finiteness and the limitation of both which is contradictory to the very idea of the Absolute unity of the Essence. (A.P.).',
 "'_Samad'_, i.e., independent of any one - All perfect - The One to Whom recourse is made by everything Eternal for its needs, both for existence and for perfection. The One who needs no subsistence of any kind – Self existing to understand Whose existence every mind is drowned in marvel and wonder. Nothing is hidden from His all-enveloping Knowledge - Is not accommodable in anything not even in intellect, Infinite in all aspects of the existence and attributes.\n\nIn fact, the names or the attributes mentioned to describe His existence or its nature, are unconveyable in their fullness hence cannot be translated to give the correct or the fullest sense or the meaning of the terms.\n\nAll the meanings attached to this term 'Samad' are the necessary properties of the actual meaning given in the note on the authority of Holy Imam Ali Ibn al-Husayn Az-Zain al-Abideen of the Ahl Al-Bayt. (A.P.).",
 "'_Samad'_, i.e., independent of any one - All perfect - The One to Whom recourse is made by everything Eternal for its needs, both for existence and for perfection. The One who needs no subsistence of any kind – Self existing to understand Whose existence every mind is drowned in marvel and wonder. Nothing is hidden from His all-enveloping Knowledge - Is not accommodable in anything not even in intellect, Infinite in all aspects of the existence and attributes.\n\nIn fact, the names or the attributes mentioned to describe His existence or its nature, are unconveyable in their fullness hence cannot be translated to give the correct or the fullest sense or the meaning of the terms.\n\nAll the meanings attached to this term 'Samad' are the necessary properties of the actual meaning given in the note on the authority of Holy Imam Ali Ibn al-Husayn Az-Zain al-Abideen of the Ahl Al-Bayt. (A.P.).",
 "'_Samad'_, i.e., independent of any one - All perfect - The One to Whom recourse is made by everything Eternal for its needs, both for existence and for perfection. The One who needs no subsistence of any kind – Self existing to understand Whose existence every mind is drowned in marvel and wonder. Nothing is hidden from His all-enveloping Knowledge - Is not accommodable in anything not even in intellect, Infinite in all aspects of the existence and attributes.\n\nIn fact, the names or the attributes mentioned to describe His existence or its nature, are unconveyable in their fullness hence cannot be translated to give the correct or the fullest sense or the meaning of the terms.\n\nAll the meanings attached to this term 'Samad' are the necessary properties of the actual meaning given in the note on the authority of Holy Imam Ali Ibn al-Husayn Az-Zain al-Abideen of the Ahl Al-Bayt. (A.P.).",
 'See <{["Q", "112:3"]}>',
 'See <{["Q", "112:3"]}>',
 'See <{["Q", "112:3"]}>',
 '\'_Abu_-_Lahab\'_, i.e., the father of the flames whose name was Abd al-Uzza, was a man of a fiery temperament. The Holy Prophet as commanded by God gathered all his relatives to announce for the first time openly, that he was the apostle of God. Abu-Lahab was also in the assembly, for he was the uncle of the Holy Prophet (he was a cousin of Abdul Muttalib, the Holy Prophet\'s grandfather). When the Holy Prophet addressing the assembly asked \'\'_If I tell you that there is a huge army of an enemy camping at the foot of this mountain on the other side of it, will ye believe me_\'" The whole assembly unanimously said \'\'_Certainly we will believe, for thou hast never told a lie._\'" \'\'Then" said the Holy Prophet \'\'_I have come from God as a Warner to preach the Unity of the Lord!_" Hearing this Abu-Lahab exclaimed \'\'_Perdition to thee_!" _Was it for this thou summoned us all?_" This verse refers to the heavenly curse invoked on the two hands of Abu-Lahab with which he raised the stone to throw it on the Holy Prophet.\n\nAbu-Lahab was one of the worst enemies of the Holy Prophet for preaching Islam. Once Abu-Lahab was found going behind the Holy Prophet passing through the market-place called \'Zul Mujaz\' shouting behind, to the people not to listen to the Holy Prophet saying that he was a mad man and pelting stones on him, the Holy Prophet walked with bleeding wounds in his heels.\n\nAbu-Lahab died a week after the defeat of Meccans at Badr with some contagious disease and since his body gave out an unbearable foul smell, was left unburied for three days and at last some slaves were hired to bury it.\n\nThe verse prophesies perdition for Abu-Lahab both in this life and in the hereafter.\n\nAbu-Lahab and his wife being specifically mentioned as the cursed ones among the enemies of Islam, is just to emphasise that no relationship whatsoever even with the Holy Prophet can be of any avail when the person lacks in faith. It is well said:\n\nCertainly, did cause fall to Abu-Lahab, the noble Shirk, polytheism.\n\nAnd certainly, raised Salman al-Farsi - his Islam - to the state of being one of the Holy Ahl Al-Bayt. (A.P.).',

In [11]:
def check_citations_intact(source: str, translation: str) -> bool:
    import re
    pattern = re.compile(r'<\{\["([\w]+)"\s*,\s*("[\w:]+"|\d+)\]\}>')
    return pattern.findall(source) == pattern.findall(translation)

In [12]:
print(check_citations_intact('See <{["Q", "112:3"]}>', 'Lihat <{["Q", "112:3"]}>'))
print(check_citations_intact('and is followed by the Successor,<{["F", 1]}>', 'dan diikuti Penerusnya,<{["F", 1]}>'))

True
True

In [15]:
intact_citations = df.apply(lambda row: check_citations_intact(row['input.text'], row['result.translation']), axis=1)
display(intact_citations.describe())
df[~intact_citations].groupby(['setting.prompt.name', 'setting.model'])[
    ['setting.prompt.name', 'setting.model', 'input.text', 'result.translation']
].describe()

count      181
unique       2
top       True
freq       180
dtype: object

                                  setting.prompt.name                       \
                                                count unique      top freq
setting.prompt.name setting.model
minimal             qwen3-8b                        1      1  minimal    1

                                  setting.model                        \
                                          count unique       top freq
setting.prompt.name setting.model
minimal             qwen3-8b                  1      1  qwen3-8b    1

                                  input.text         \
                                       count unique
setting.prompt.name setting.model
minimal             qwen3-8b               1      1

                                                                                                \
                                                                                           top
setting.prompt.name setting.model
minimal             qwen3-8b       When the Quraysh have been granted such great blessings ...

                                       result.translation         \
                                  freq              count unique
setting.prompt.name setting.model
minimal             qwen3-8b         1                  1      1

                                                                                                \
                                                                                           top
setting.prompt.name setting.model
minimal             qwen3-8b       Ketika Quraysh telah diberikan berbagai berkat yang besa...


                                  freq
setting.prompt.name setting.model
minimal             qwen3-8b         1

In [39]:
df[~intact_citations]['input.text'].apply(print)
print("====")
df[~intact_citations]['result.translation'].apply(print)

When the Quraysh have been granted such great blessings they must gratefully worship the Lord of the Ka'ba, who in spite of their land being only a desert and thus unproductive, provides them with every kind of good food and the other provisions of life through merchandise and the pilgrimage which brings to their very door, their needs through the great multitudes of the visitors who come there also to buy and sell, and God had protected them from the most formidable enemy Abraha, but for God's help they would have been destroyed and their city would have been lost, the Ka'ba, on account of which they are honoured and respected, their city would have been laid waste by the enemy, they with their wives and children would have been taken as captives, and enslaved and sold away to the others and thus they would have been tom away from their kith and kin and their tribe as a whole would have been disintegrated and wiped out of existence.

This was an open admonition to the Quraysh who had been in the start of the ministry of the Holy Prophet, the most inveterate enemies of the Apostle of God and the message of the Unity of the Lord which he preached. It was as well a warning inviting their attention to the Mighty power of God who could also destroy them and humiliate them as he did act with their mighty foe Abraha<{["F", 1]}>.
====
Ketika Quraysh telah diberikan berbagai berkat yang besar, mereka harus beribadat dengan rasa syukur kepada Tuhan Ka'ba, yang meskipun tanah mereka hanyalah gurun dan tidak menghasilkan sesuatu apa pun, tetapi memberikan kepada mereka segala jenis makanan yang baik dan kebutuhan hidup lainnya melalui perdagangan dan ibadah haji yang membawa kebutuhan mereka ke pintu rumah mereka sendiri melalui jumlah besar pengunjung yang datang ke sana juga untuk membeli dan menjual. Dan Tuhan telah melindungi mereka dari musuh terkuat, yaitu Abraha. Jika tidak ada bantuan Tuhan, mereka akan binasa dan kota mereka, Ka'ba, yang merupakan sumber kehormatan dan penghargaan mereka, akan dihancurkan oleh musuh. Mereka bersama istri, anak-anak, akan ditawan, dijadikan budak, dan dijual ke pihak lain, sehingga mereka akan terpisah dari keluarga dan kerabat mereka. Seluruh suku mereka akan hancur dan lenyap dari muka bumi.

Ini adalah peringatan terbuka kepada Quraysh yang sedang berada di awal masa pelayanan Nabi yang suci, para musuh terbesar dari Rasulullah dan pesan tentang kesatuan Tuhan yang diajarkan-Nya. Ini juga merupakan peringatan yang memanggil perhatian mereka terhadap kekuatan besar Tuhan, yang juga dapat menghancurkan dan mempermalukan mereka seperti yang telah dilakukan terhadap musuh besar mereka, yaitu Abraha.

126    None
Name: result.translation, dtype: object

In [59]:
with pd.option_context('display.max_colwidth', None):
    display(df[["input.text", "result.translation", "result.rating", "setting.model", "setting.prompt.name"]
        ].sort_values("result.rating").tail(30))

,input.text,result.translation,result.rating,setting.model,setting.prompt.name
162,"See <{[""Q"", ""104:6""]}>","Lihat <{[""Q"", ""104:6""]}>",0.307317,qwen3-8b,minimal
169,"See <{[""Q"", ""104:8""]}>","Lihat <{[""Q"", ""104:8""]}>",0.309938,qwen3-8b,professional
168,"See <{[""Q"", ""104:8""]}>","Lihat <{[""Q"", ""104:8""]}>",0.309938,qwen3-8b,minimal
51,When Abu-Lahab will be in the hell-fire and then he would realise the return for his disbelief and tyranny and know of what value was his wealth.,"Ketika Abu-Lahab berada di api neraka, nanti dia akan menyadari balasan atas kekafiran dan siksa yang dia lakukan, dan dia akan mengetahui seberapa bernilainya harta benda yang dia miliki.",0.314910,qwen3-8b,minimal
147,"See <{[""Q"", ""104:1""]}>","Lihat <{[""Q"", ""104:1""]}>",0.335875,qwen3-8b,minimal
148,"See <{[""Q"", ""104:1""]}>","Lihat <{[""Q"", ""104:1""]}>",0.335875,qwen3-8b,professional
120,"The protection, safety and the honour, the Quraysh enjoyed was due to the Holy Ka'ba being in their city and their being its guardians.","Perlindungan, keselamatan, dan kehormatan yang dinikmati oleh Quraysh adalah karena Ka'ba yang suci berada di kota mereka dan mereka menjadi penjaganya.",0.339310,qwen3-8b,minimal
121,"The protection, safety and the honour, the Quraysh enjoyed was due to the Holy Ka'ba being in their city and their being its guardians.","Perlindungan, keselamatan, dan kehormatan yang dinikmati oleh Quraysh adalah karena Ka'ba yang suci berada di kota mereka dan mereka menjadi penjaganya.",0.339310,qwen3-8b,professional
122,"The protection, safety and the honour, the Quraysh enjoyed was due to the Holy Ka'ba being in their city and their being its guardians.","Perlindungan, keselamatan, dan kehormatan yang dinikmati oleh Quraysh adalah karena Ka'ba yang suci berada di kota mereka dan mereka menjadi penjaganya.",0.339310,qwen3-8b,verbose
135,"God sent upon the army, a huge host of some tiny birds with small stones in their beaks.",Tuhan mengirimkan kepada pasukan itu sebuah rombongan besar dari beberapa burung kecil yang memiliki batu kecil di paruh mereka.,0.343960,qwen3-8b,minimal
53,When Abu-Lahab will be in the hell-fire and then he would realise the return for his disbelief and tyranny and know of what value was his wealth.,"Ketika Abu-Lahab berada di api neraka, nanti dia akan menyadari balasan atas kekafiran dan siksa yang dia lakukan, dan mengetahui seberapa bernilainya harta benda yang dia miliki.",0.357418,qwen3-8b,verbose
13,Satan Who whispers evil into the minds of men and leaves them to suffer the consequences of obeying his instigations to evil.,Satan yang menggoda manusia dengan bisikan kejahatan dan meninggalkan mereka menderita akibat dari mengikuti ajakannya untuk berbuat jahat.,0.362918,qwen3-8b,professional
132,"See <{[""Q"", ""105:1""]}>","Lihat <{[""Q"", ""105:1""]}>",0.372088,qwen3-8b,minimal
133,"See <{[""Q"", ""105:1""]}>","Lihat <{[""Q"", ""105:1""]}>",0.372088,qwen3-8b,professional
43,"See <{[""Q"", ""112:3""]}>","Lihat <{[""Q"", ""112:3""]}>",0.374072,qwen3-8b,professional
42,"See <{[""Q"", ""112:3""]}>","Lihat <{[""Q"", ""112:3""]}>",0.374072,qwen3-8b,minimal
14,Satan Who whispers evil into the minds of men and leaves them to suffer the consequences of obeying his instigations to evil.,Setan yang menggoda manusia dengan bisikan kejahatan dan meninggalkan mereka menderita akibat dari mengikuti ajakan kejahatan-Nya.,0.374963,qwen3-8b,verbose
85,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,professional
84,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
82,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,professional
81,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
79,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,professional
73,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,professional
76,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,professional
75,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
72,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
78,"See <{[""Q"", ""109:1""]}>","Lihat <{[""Q"", ""109:1""]}>",0.376887,qwen3-8b,minimal
52,When Abu-Lahab will be in the hell-fire and then he would realise the return for his disbelief and tyranny and know of what value was his wealth.,"Ketika Abu-Lahab berada di api neraka, nanti dia akan menyadari balasan atas kekafirannya dan siksaannya, dan mengetahui seberapa bernilainya harta benda yang dimilikinya.",0.387317,qwen3-8b,professional
63,"See <{[""Q"", ""110:1""]}>","Lihat <{[""Q"", ""110:1""]}>",0.415419,qwen3-8b,minimal
64,"See <{[""Q"", ""110:1""]}>","Lihat <{[""Q"", ""110:1""]}>",0.415419,qwen3-8b,professional

,input.text,result.translation,result.rating,setting.model,setting.prompt.name
29,Those who practise magical arts of blowing on knots-the favourite witchcraft generally practised by perverted woman which creates psychological disturbances.,Yang mempraktikkan seni magis menghembuskan napas ke simpul-simpul-kesenian penyihir yang paling disukai umumnya dilakukan oleh wanita yang tergoda yang menciptakan gangguan psikologis.,-0.621145,qwen3-8b,verbose
27,Those who practise magical arts of blowing on knots-the favourite witchcraft generally practised by perverted woman which creates psychological disturbances.,"Orang-orang yang mempraktikkan ilmu sihir menghembuskan napas ke simpul-simpul—sihir penyihir yang paling disukai umumnya dilakukan oleh wanita yang tergoda, yang menciptakan gangguan psikologis.",-0.529700,qwen3-8b,minimal
28,Those who practise magical arts of blowing on knots-the favourite witchcraft generally practised by perverted woman which creates psychological disturbances.,Yang mempraktikkan seni magis meniup simpul-simpul - sihir penyihir yang paling disukai umumnya dilakukan oleh wanita yang terdistorsi yang menciptakan gangguan psikologis.,-0.369753,qwen3-8b,professional
58,"An angel got her strangled by the very rope she used to hang around her neck, and she died. On the Day of Judgment, the wicked woman will be with a rope of the hell-fire hanging around her neck.","Seorang malaikat menggantungkan tali yang sama yang digunakannya menggantungkan lehernya sendiri, dan dia mati. Pada Hari Kiamat, wanita jahat itu akan berada di sisi tali api neraka yang menggantungkan lehernya.",-0.338347,qwen3-8b,professional
141,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered lifeless, useless and loathsome - like the refuse of an eaten food.","'_Asfin Makool'_ , yaitu, rumput yang telah dimakan, yaitu, diubah menjadi tidak bernyawa, tidak berguna, dan menjijikkan - seperti sisa makanan yang telah dimakan.",-0.329658,qwen3-8b,minimal
20,"'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).","'_Falaq'_ yaitu, memisahkan, di sini berarti memisahkan gelap, yaitu, fajar - mungkin berarti penghancur dari efek jahat sihir hitam, yaitu, gelap atau efek musibah sihir. Surah ini diturunkan untuk menghilangkan efek jahat dari sihir atau perdukunan apa pun.\n\nAdat-istiadat, Nabi yang suci terkena sihir oleh para dukun sedemikian rupa hingga ia sendiri tidak menyadari apa yang sedang ia lakukan - mengurangi Nabi terakhir Tuhan sampai pada kondisi di mana tongkat Musa akan lebih unggul darinya untuk menghilangkan sihir tersebut.\n\nAdat-istiadat semacam ini jelas telah dibuat oleh elemen-elemen yang suka berbuat jahat yang ingin menurunkan posisi mulia Nabi yang suci sampai ke tingkat karakter dan keyakinan mereka sendiri. Jelas saja, ada adat-istiadat tentang manfaat membaca Surah ini dan Surah-surah sebelumnya serta sesudahnya dalam menghilangkan efek sihir apa pun yang mungkin terjadi. (A.P.).",-0.324726,qwen3-8b,verbose
19,"'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).","'_Falaq'_ yaitu, memisahkan, di sini berarti memisahkan gelap, yaitu fajar - mungkin berarti penghancur dari efek jahat sihir, yaitu gelap atau efek musibah dari sihir. Surah ini diturunkan untuk menghilangkan efek jahat dari sihir atau perdukunan apa pun.\n\nAdat-istiadat, Nabi yang mulia dihipnotis oleh para dukun sedemikian rupa hingga ia sendiri tidak menyadari apa yang sedang ia lakukan - mengurangi Nabi terakhir Tuhan sampai pada kondisi di mana tongkat Musa akan lebih unggul darinya untuk menghilangkan sihir tersebut.\n\nAdat-istiadat semacam ini tentu saja dibuat oleh elemen-elemen yang suka berbuat jahat yang ingin mengurangi posisi mulia Nabi yang suci sampai ke tingkat karakter dan keyakinan mereka sendiri. Jelas saja, terdapat adat-istiadat tentang manfaat membaca Surah ini dan Surah-surah sebelumnya serta sesudahnya dalam menghilangkan efek sihir yang mungkin terjadi. (A.P.).",-0.320047,qwen3-8b,professional
142,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered lifeless, useless and loathsome - like the refuse of an eaten food.","'_Asfin Makool'_ yaitu, rumput yang telah dimakan, yaitu, diubah menjadi tidak hidup, tidak berguna dan menjijikkan - seperti sisa makanan yang telah dimakan.",-0.300564,qwen3-8b,professional
167,"It will cover the individual, all around him, i.e., the punishment will be to every part of the individual, outer or the innermost, which will be drowned in the fire, and the columns of the fire will be rising even high above him.","Ini akan menutupi individu, di sekelilingnya, yaitu hukuman akan menjangkau setiap bagian dari individu, luar atau yang paling dalam, yang akan tenggelam dalam api, dan tiang-tiang api akan terus meninggi bahkan di atasnya.",-0.300341,qwen3-8b,verbose
18,"'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).","'_Falaq_' yaitu, memisahkan, di sini berarti memisahkan gelap, yaitu fajar — mungkin berarti pengusung efek buruk dari sihir, yaitu gelap atau efek buruk dari ilmu hitam. Surah ini diturunkan untuk menghilangkan efek buruk dari sihir atau perdukunan apa pun.\n\nAdat-istiadat, yaitu Nabi yang suci terkena ilmu hitam oleh para dukun hingga ia sendiri tidak menyadari apa yang sedang ia lakukan — mengurangi Nabi terakhir Tuhan sampai ke tingkat di mana tongkat Musa akan lebih unggul darinya untuk menghilangkan ilmu hitam tersebut.\n\nAdat-istiadat semacam ini jelas telah dibuat oleh elemen-elemen yang suka berbuat jahat yang ingin menurunkan posisi mulia Nabi yang suci ke tingkat karakter dan keyakinan mereka sendiri. Tidak diragukan lagi, ada adat-istiadat tentang manfaat membaca Surah ini dan Surah-surah sebelumnya serta sesudahnya dalam menghilangkan efek mungkin dari sihir apa pun. (A.P.).",-0.295200,qwen3-8b,minimal
59,"An angel got her strangled by the very rope she used to hang around her neck, and she died. On the Day of Judgment, the wicked woman will be with a rope of the hell-fire hanging around her neck.","Seorang malaikat menggantungkan tali yang sama yang pernah digunakan untuk menggantungkan lehernya sendiri, sehingga ia mati. Pada Hari Kiamat, wanita jahat itu akan berada di sisi tali api neraka yang menggantung di lehernya.",-0.285635,qwen3-8b,verbose
143,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered lifeless, useless and loathsome - like the refuse of an eaten food.","'_Asfin Makool'_ yaitu, rumput yang telah dimakan, yaitu, diubah menjadi tidak bernyawa, tidak berguna dan menjijikkan - seperti sisa makanan yang telah dimakan.",-0.274496,qwen3-8b,verbose
38,"'_Samad'_, i.e., independent of any one - All perfect - The One to Whom recourse is made by everything Eternal for its needs, both for existence and for perfection. The One who needs no subsistence of any kind – Self existing to understand Whose existence every mind is drowned in marvel and wonder. Nothing is hidden from His all-enveloping Knowledge - Is not accommodable in anything not even in intellect, Infinite in all aspects of the existence and attributes.\n\nIn fact, the names or the attributes mentioned to describe His existence or its nature, are unconveyable in their fullness hence cannot be translated to give the correct or the fullest sense or the meaning of the terms.\n\nAll the meanings attached to this term 'Samad' are the necessary properties of the actual meaning given in the note on the authority of Holy Imam Ali Ibn al-Husayn Az-Zain al-Abideen of the Ahl Al-Bayt. (A.P.).","'_Samad_', yaitu, terlepas dari satu - Semua sempurna - Yang satu yang diharapkan oleh segala sesuatu abadi untuk kebutuhannya, baik untuk keberadaan maupun kesempurnaan. Yang tidak memerlukan subsistensi apa pun - Yang ada secara sendiri untuk memahami keberadaan-Nya, setiap pikiran tenggelam dalam keajaiban dan kekaguman. Tidak ada yang tersembunyi dari Pengetahuan-Nya yang menyelubungi segalanya - Tidak dapat diakomodasi dalam sesuatu, bahkan dalam akal, Tak terbatas dalam segala aspek keberadaan dan sifat-sifat-Nya.\n\nSebenarnya, nama-nama atau sifat-sifat yang disebutkan untuk menggambarkan keberadaan-Nya atau sifat-sifat-Nya, tidak dapat menyampaikan maknanya secara utuh, sehingga tidak dapat diterjemahkan untuk memberikan makna yang benar atau paling lengkap dari istilah-istilah tersebut.\n\nSemua makna yang terkait dengan istilah ini 'Samad' adalah sifat-sifat yang diperlukan dari makna sebenarnya yang diberikan dalam catatan tersebut berdasarkan wewenang dari Imam yang suci Ali Ibn al-Husayn Az-Zain al-Abideen dari Ahl Al-Bayt. (A.P.).",-0.266869,qwen3-8b,verbose
41,"Nothing has come out of Him, i.e., He has not begotten any issue. There is no son or daughter born of Him. To assign a son or a daughter to Him, is the greatest blasphemy. Nor is He born of any other being. There is no match or equal to Him in any aspect, in any meaning or in any sense of any of the divine qualities. To assign any wife or mate to Him is a gross blasphemy against His All-Divine Being.\n\nSince man is a limited being and he with his inherent limitations cannot correctly conceive of things unknown to him but through some examples in the terms used for the things physical, certain terms have to be helplessly used, otherwise the essence or the qualities of God are beyond any description or definition with any amount of human knowledge with the maximum wealth of the linguistic expressions which man can ever coin in the mine of his intellect. Anything man coins would be incomparably insignificant and hopelessly imperfect and miserably inadequate to deal with the matter connected with the knowledge of the Infinite.","Tidak ada yang keluar darinya, yaitu Ia tidak memiliki anak. Tidak ada anak atau putri yang dilahirkan darinya. Untuk memberikan anak atau putri kepada-Nya adalah kesombongan terbesar. Dan Ia tidak dilahirkan oleh makhluk lain. Tidak ada yang setara atau menyamai-Nya dalam segala hal, dalam segala makna atau dalam segala arti dari setiap sifat ilahi. Untuk memberikan isteri atau pasangan kepada-Nya adalah kesombongan besar terhadap Keilahian-Nya yang Maha Sempurna.\n\nKarena manusia adalah makhluk terbatas dan ia dengan keterbatasan bawaannya tidak dapat memahami dengan benar hal-hal yang tidak dikenalnya, tetapi melalui beberapa contoh dalam istilah-istilah yang digunakan untuk hal-hal fisik, maka beberapa istilah harus digunakan secara membual, sebaliknya esensi atau sifat-sifat Tuhan tidak dapat dijelaskan atau didefinisikan dengan apa pun dari pengetahuan manusia, bahkan dengan jumlah pengetahuan manusia yang paling kaya dalam kandang pikirannya. Segala sesuatu yang diciptakan manusia akan jauh lebih tidak relevan dan tidak mungkin serta sangat tidak memadai untuk menghadapi masalah yang berkaitan dengan pengetahuan tentang Yang Tak Terbatas.",-0.247099,qwen3-8b,verbose
140,"The birds dropped the stones which they had brought in their beaks upon the soldiers. '_Sijjeel'_ a stone of baked clay<{[""F"", 1]}>.","Burung-burung melemparkan batu-batu yang mereka bawa di mulut mereka kepada para prajurit. '_Sijjeel'_ sebuah batu dari tanah liat yang dibakar<{[""F"", 1]}>.",-0.237072,qwen3-8b,verbose
39,"Nothing has come out of Him, i.e., He has not begotten any issue. There is no son or daughter born of Him. To assign a son or a daughter to Him, is the greatest blasphemy. Nor is He born of any other being. There is no match or equal to Him in any aspect, in any meaning or in any sense of any of the divine qualities. To assign any wife or mate to Him is a gross blasphemy against His All-Divine Being.\n\nSince man is a limited being and he with his inherent limitations cannot correctly conceive of things unknown to him but through some examples in the terms used for the things physical, certain terms have to be helplessly used, otherwise the essence or the qualities of God are beyond any description or definition with any amount of human knowledge with the maximum wealth of the linguistic expressions which man can ever coin in the mine of his intellect. Anything man coins would be incomparably insignificant and hopelessly imperfect and miserably inadequate to deal with the matter connected with the knowledge of the Infinite.","Tidak ada yang keluar dari-Nya, yaitu, Ia tidak memiliki anak. Tidak ada putra atau putri yang lahir dari-Nya. Untuk memberikan seorang putra atau putri kepada-Nya adalah dosa terbesar. Demikian pula, Ia tidak dilahirkan oleh makhluk lain. Tidak ada yang dapat menyamai-Nya dalam segala hal, dalam segala makna, atau dalam segala arti dari sifat-sifat ilahi. Untuk memberikan seorang istri atau pasangan kepada-Nya adalah dosa besar terhadap Keilahian-Nya yang Maha Sempurna.\n\nKarena manusia adalah makhluk terbatas, dan ia dengan keterbatasan bawaannya tidak dapat memahami dengan benar sesuatu yang tidak dikenalnya, tetapi melalui beberapa contoh dalam istilah yang digunakan untuk hal-hal fisik, beberapa istilah harus digunakan secara tidak terhindarkan, sebaliknya esensi atau sifat-sifat Tuhan tidak dapat dijelaskan atau didefinisikan dengan apa pun dari pengetahuan manusia, bahkan dengan kaya raya ekspresi linguistik yang dapat diciptakan oleh manusia dari tambang pikirannya. Segala sesuatu yang diciptakan manusia akan jauh lebih tidak relevan, tidak mungkin, dan sangat tidak memadai untuk menghadapi masalah yang berkaitan dengan pengetahuan tentang Yang Tak Terbatas.",-0.232454,qwen3-8b,minimal
16,"Be the evil doers, the Jinns or human beings. It is a well-known fact that among the forces hidden from the human eye, which are active in the world, there are good and also bad ones among them. Jinns, like Satan are spiritual beings<{[""F"", 1]}>.\n\n**The End**","Jadi menjadi pelaku kejahatan, Jinns atau manusia. Ini adalah fakta yang sudah dikenal bahwa di antara kekuatan-kekuatan yang tersembunyi dari mata manusia, yang aktif di dunia ini, terdapat yang baik dan juga yang buruk di antaranya. Jinns, seperti Iblis, adalah makhluk spiritual<{[""F"", 1]}>.\n\n**Akhir**",-0.230207,qwen3-8b,professional
153,"The root of '_Hutama'_ is '_Hatima'_, i.e., getting rendered or broken into pieces, i.e., it will be crushed, destroyed and thrown into Hell before the eyes of those who spent their lives in amassing it and prided over it and got intoxicated of it, thinking it to be of a permanent value to them - deprived the others of their share, did not spend of it for the benefit of the others who suffered miserably for want of something of it. Besides they had been so much maddened by the acquisition of their wealth they had forgotten God who had allowed them to have it, and thought themselves totally independent of Him and acted as their devilish passions dictated to them, never cared for the limits prescribed by the Lord.\n\n'_Hutama'_ that which will break or destroy it, is the Hell-fire.","Akar dari '_Hutama_' adalah '_Hatima_', yaitu proses menjadi terkena dampak atau hancur berkeping-keping, yaitu akan dihancurkan, dihancurkan, dan dilempar ke Neraka di hadapan orang-orang yang menghabiskan hidup mereka untuk mengumpulkan dan membanggakan diri atasnya serta terlena olehnya, menganggapnya memiliki nilai yang kekal bagi mereka, mengambil bagian orang lain, tidak menghabiskan untuk kebaikan orang lain yang menderita secara menderita karena kekurangan sesuatu dari itu. Selain itu, mereka terlalu terpukau oleh pengumpulan kekayaan mereka hingga lupa akan Tuhan yang telah memberikan kekayaan itu kepada mereka, dan menganggap diri mereka benar-benar mandiri dari-Nya serta bertindak sesuai dengan hasrat iblis yang mengendalikan mereka, tidak pernah memperhatikan batas-batas yang ditetapkan oleh Tuhan.\n\n'_Hutama_' yang akan memecah atau menghancurkannya adalah api Neraka.",-0.227052,qwen3-8b,minimal

In [60]:
with pd.option_context('display.max_colwidth', None):
    display(df[["input.text", "result.translation", "result.rating", "setting.model", "setting.prompt.name"]
        ].sort_values("result.rating").head(30))

,input.text,result.translation,result.rating,setting.model,setting.prompt.name
29,Those who practise magical arts of blowing on knots-the favourite witchcraft generally practised by perverted woman which creates psychological disturbances.,Yang mempraktikkan seni magis menghembuskan napas ke simpul-simpul-kesenian penyihir yang paling disukai umumnya dilakukan oleh wanita yang tergoda yang menciptakan gangguan psikologis.,-0.621145,qwen3-8b,verbose
27,Those who practise magical arts of blowing on knots-the favourite witchcraft generally practised by perverted woman which creates psychological disturbances.,"Orang-orang yang mempraktikkan ilmu sihir menghembuskan napas ke simpul-simpul—sihir penyihir yang paling disukai umumnya dilakukan oleh wanita yang tergoda, yang menciptakan gangguan psikologis.",-0.529700,qwen3-8b,minimal
28,Those who practise magical arts of blowing on knots-the favourite witchcraft generally practised by perverted woman which creates psychological disturbances.,Yang mempraktikkan seni magis meniup simpul-simpul - sihir penyihir yang paling disukai umumnya dilakukan oleh wanita yang terdistorsi yang menciptakan gangguan psikologis.,-0.369753,qwen3-8b,professional
58,"An angel got her strangled by the very rope she used to hang around her neck, and she died. On the Day of Judgment, the wicked woman will be with a rope of the hell-fire hanging around her neck.","Seorang malaikat menggantungkan tali yang sama yang digunakannya menggantungkan lehernya sendiri, dan dia mati. Pada Hari Kiamat, wanita jahat itu akan berada di sisi tali api neraka yang menggantungkan lehernya.",-0.338347,qwen3-8b,professional
141,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered lifeless, useless and loathsome - like the refuse of an eaten food.","'_Asfin Makool'_ , yaitu, rumput yang telah dimakan, yaitu, diubah menjadi tidak bernyawa, tidak berguna, dan menjijikkan - seperti sisa makanan yang telah dimakan.",-0.329658,qwen3-8b,minimal
20,"'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).","'_Falaq'_ yaitu, memisahkan, di sini berarti memisahkan gelap, yaitu, fajar - mungkin berarti penghancur dari efek jahat sihir hitam, yaitu, gelap atau efek musibah sihir. Surah ini diturunkan untuk menghilangkan efek jahat dari sihir atau perdukunan apa pun.\n\nAdat-istiadat, Nabi yang suci terkena sihir oleh para dukun sedemikian rupa hingga ia sendiri tidak menyadari apa yang sedang ia lakukan - mengurangi Nabi terakhir Tuhan sampai pada kondisi di mana tongkat Musa akan lebih unggul darinya untuk menghilangkan sihir tersebut.\n\nAdat-istiadat semacam ini jelas telah dibuat oleh elemen-elemen yang suka berbuat jahat yang ingin menurunkan posisi mulia Nabi yang suci sampai ke tingkat karakter dan keyakinan mereka sendiri. Jelas saja, ada adat-istiadat tentang manfaat membaca Surah ini dan Surah-surah sebelumnya serta sesudahnya dalam menghilangkan efek sihir apa pun yang mungkin terjadi. (A.P.).",-0.324726,qwen3-8b,verbose
19,"'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).","'_Falaq'_ yaitu, memisahkan, di sini berarti memisahkan gelap, yaitu fajar - mungkin berarti penghancur dari efek jahat sihir, yaitu gelap atau efek musibah dari sihir. Surah ini diturunkan untuk menghilangkan efek jahat dari sihir atau perdukunan apa pun.\n\nAdat-istiadat, Nabi yang mulia dihipnotis oleh para dukun sedemikian rupa hingga ia sendiri tidak menyadari apa yang sedang ia lakukan - mengurangi Nabi terakhir Tuhan sampai pada kondisi di mana tongkat Musa akan lebih unggul darinya untuk menghilangkan sihir tersebut.\n\nAdat-istiadat semacam ini tentu saja dibuat oleh elemen-elemen yang suka berbuat jahat yang ingin mengurangi posisi mulia Nabi yang suci sampai ke tingkat karakter dan keyakinan mereka sendiri. Jelas saja, terdapat adat-istiadat tentang manfaat membaca Surah ini dan Surah-surah sebelumnya serta sesudahnya dalam menghilangkan efek sihir yang mungkin terjadi. (A.P.).",-0.320047,qwen3-8b,professional
142,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered lifeless, useless and loathsome - like the refuse of an eaten food.","'_Asfin Makool'_ yaitu, rumput yang telah dimakan, yaitu, diubah menjadi tidak hidup, tidak berguna dan menjijikkan - seperti sisa makanan yang telah dimakan.",-0.300564,qwen3-8b,professional
167,"It will cover the individual, all around him, i.e., the punishment will be to every part of the individual, outer or the innermost, which will be drowned in the fire, and the columns of the fire will be rising even high above him.","Ini akan menutupi individu, di sekelilingnya, yaitu hukuman akan menjangkau setiap bagian dari individu, luar atau yang paling dalam, yang akan tenggelam dalam api, dan tiang-tiang api akan terus meninggi bahkan di atasnya.",-0.300341,qwen3-8b,verbose
18,"'_Falaq'_ i.e., cleaving, here means cleaving of the darkness, i.e., dawn - it may mean destroyer of the evil effects of black art, i.e., the darkness or the calamitous effect of witchcraft. This Surah was revealed to undo any evil effects of any witchcraft or sorcery.\n\nThe Tradition, the Holy Prophet being enchanted by the sorcerers in such a manner that he was himself unconscious what he was actually doing - reduces the Last Prophet of God to such a state that the Rod of Moses would be superior to him to undo the sorcery.\n\nThese sorts of Traditions undoubtedly have been fabricated by the mischievous elements who wanted to reduce the sublime position of the Holy Prophet to their own level of character and belief. Of course, there are traditions about the utility of the recitation of this and the previous, and the next suras in dispelling the possible effect of any witchcraft. (A.P.).","'_Falaq_' yaitu, memisahkan, di sini berarti memisahkan gelap, yaitu fajar — mungkin berarti pengusung efek buruk dari sihir, yaitu gelap atau efek buruk dari ilmu hitam. Surah ini diturunkan untuk menghilangkan efek buruk dari sihir atau perdukunan apa pun.\n\nAdat-istiadat, yaitu Nabi yang suci terkena ilmu hitam oleh para dukun hingga ia sendiri tidak menyadari apa yang sedang ia lakukan — mengurangi Nabi terakhir Tuhan sampai ke tingkat di mana tongkat Musa akan lebih unggul darinya untuk menghilangkan ilmu hitam tersebut.\n\nAdat-istiadat semacam ini jelas telah dibuat oleh elemen-elemen yang suka berbuat jahat yang ingin menurunkan posisi mulia Nabi yang suci ke tingkat karakter dan keyakinan mereka sendiri. Tidak diragukan lagi, ada adat-istiadat tentang manfaat membaca Surah ini dan Surah-surah sebelumnya serta sesudahnya dalam menghilangkan efek mungkin dari sihir apa pun. (A.P.).",-0.295200,qwen3-8b,minimal
59,"An angel got her strangled by the very rope she used to hang around her neck, and she died. On the Day of Judgment, the wicked woman will be with a rope of the hell-fire hanging around her neck.","Seorang malaikat menggantungkan tali yang sama yang pernah digunakan untuk menggantungkan lehernya sendiri, sehingga ia mati. Pada Hari Kiamat, wanita jahat itu akan berada di sisi tali api neraka yang menggantung di lehernya.",-0.285635,qwen3-8b,verbose
143,"'_Asfin Makool'_, i.e., straw eaten up, i.e., rendered lifeless, useless and loathsome - like the refuse of an eaten food.","'_Asfin Makool'_ yaitu, rumput yang telah dimakan, yaitu, diubah menjadi tidak bernyawa, tidak berguna dan menjijikkan - seperti sisa makanan yang telah dimakan.",-0.274496,qwen3-8b,verbose
38,"'_Samad'_, i.e., independent of any one - All perfect - The One to Whom recourse is made by everything Eternal for its needs, both for existence and for perfection. The One who needs no subsistence of any kind – Self existing to understand Whose existence every mind is drowned in marvel and wonder. Nothing is hidden from His all-enveloping Knowledge - Is not accommodable in anything not even in intellect, Infinite in all aspects of the existence and attributes.\n\nIn fact, the names or the attributes mentioned to describe His existence or its nature, are unconveyable in their fullness hence cannot be translated to give the correct or the fullest sense or the meaning of the terms.\n\nAll the meanings attached to this term 'Samad' are the necessary properties of the actual meaning given in the note on the authority of Holy Imam Ali Ibn al-Husayn Az-Zain al-Abideen of the Ahl Al-Bayt. (A.P.).","'_Samad_', yaitu, terlepas dari satu - Semua sempurna - Yang satu yang diharapkan oleh segala sesuatu abadi untuk kebutuhannya, baik untuk keberadaan maupun kesempurnaan. Yang tidak memerlukan subsistensi apa pun - Yang ada secara sendiri untuk memahami keberadaan-Nya, setiap pikiran tenggelam dalam keajaiban dan kekaguman. Tidak ada yang tersembunyi dari Pengetahuan-Nya yang menyelubungi segalanya - Tidak dapat diakomodasi dalam sesuatu, bahkan dalam akal, Tak terbatas dalam segala aspek keberadaan dan sifat-sifat-Nya.\n\nSebenarnya, nama-nama atau sifat-sifat yang disebutkan untuk menggambarkan keberadaan-Nya atau sifat-sifat-Nya, tidak dapat menyampaikan maknanya secara utuh, sehingga tidak dapat diterjemahkan untuk memberikan makna yang benar atau paling lengkap dari istilah-istilah tersebut.\n\nSemua makna yang terkait dengan istilah ini 'Samad' adalah sifat-sifat yang diperlukan dari makna sebenarnya yang diberikan dalam catatan tersebut berdasarkan wewenang dari Imam yang suci Ali Ibn al-Husayn Az-Zain al-Abideen dari Ahl Al-Bayt. (A.P.).",-0.266869,qwen3-8b,verbose
41,"Nothing has come out of Him, i.e., He has not begotten any issue. There is no son or daughter born of Him. To assign a son or a daughter to Him, is the greatest blasphemy. Nor is He born of any other being. There is no match or equal to Him in any aspect, in any meaning or in any sense of any of the divine qualities. To assign any wife or mate to Him is a gross blasphemy against His All-Divine Being.\n\nSince man is a limited being and he with his inherent limitations cannot correctly conceive of things unknown to him but through some examples in the terms used for the things physical, certain terms have to be helplessly used, otherwise the essence or the qualities of God are beyond any description or definition with any amount of human knowledge with the maximum wealth of the linguistic expressions which man can ever coin in the mine of his intellect. Anything man coins would be incomparably insignificant and hopelessly imperfect and miserably inadequate to deal with the matter connected with the knowledge of the Infinite.","Tidak ada yang keluar darinya, yaitu Ia tidak memiliki anak. Tidak ada anak atau putri yang dilahirkan darinya. Untuk memberikan anak atau putri kepada-Nya adalah kesombongan terbesar. Dan Ia tidak dilahirkan oleh makhluk lain. Tidak ada yang setara atau menyamai-Nya dalam segala hal, dalam segala makna atau dalam segala arti dari setiap sifat ilahi. Untuk memberikan isteri atau pasangan kepada-Nya adalah kesombongan besar terhadap Keilahian-Nya yang Maha Sempurna.\n\nKarena manusia adalah makhluk terbatas dan ia dengan keterbatasan bawaannya tidak dapat memahami dengan benar hal-hal yang tidak dikenalnya, tetapi melalui beberapa contoh dalam istilah-istilah yang digunakan untuk hal-hal fisik, maka beberapa istilah harus digunakan secara membual, sebaliknya esensi atau sifat-sifat Tuhan tidak dapat dijelaskan atau didefinisikan dengan apa pun dari pengetahuan manusia, bahkan dengan jumlah pengetahuan manusia yang paling kaya dalam kandang pikirannya. Segala sesuatu yang diciptakan manusia akan jauh lebih tidak relevan dan tidak mungkin serta sangat tidak memadai untuk menghadapi masalah yang berkaitan dengan pengetahuan tentang Yang Tak Terbatas.",-0.247099,qwen3-8b,verbose
140,"The birds dropped the stones which they had brought in their beaks upon the soldiers. '_Sijjeel'_ a stone of baked clay<{[""F"", 1]}>.","Burung-burung melemparkan batu-batu yang mereka bawa di mulut mereka kepada para prajurit. '_Sijjeel'_ sebuah batu dari tanah liat yang dibakar<{[""F"", 1]}>.",-0.237072,qwen3-8b,verbose
39,"Nothing has come out of Him, i.e., He has not begotten any issue. There is no son or daughter born of Him. To assign a son or a daughter to Him, is the greatest blasphemy. Nor is He born of any other being. There is no match or equal to Him in any aspect, in any meaning or in any sense of any of the divine qualities. To assign any wife or mate to Him is a gross blasphemy against His All-Divine Being.\n\nSince man is a limited being and he with his inherent limitations cannot correctly conceive of things unknown to him but through some examples in the terms used for the things physical, certain terms have to be helplessly used, otherwise the essence or the qualities of God are beyond any description or definition with any amount of human knowledge with the maximum wealth of the linguistic expressions which man can ever coin in the mine of his intellect. Anything man coins would be incomparably insignificant and hopelessly imperfect and miserably inadequate to deal with the matter connected with the knowledge of the Infinite.","Tidak ada yang keluar dari-Nya, yaitu, Ia tidak memiliki anak. Tidak ada putra atau putri yang lahir dari-Nya. Untuk memberikan seorang putra atau putri kepada-Nya adalah dosa terbesar. Demikian pula, Ia tidak dilahirkan oleh makhluk lain. Tidak ada yang dapat menyamai-Nya dalam segala hal, dalam segala makna, atau dalam segala arti dari sifat-sifat ilahi. Untuk memberikan seorang istri atau pasangan kepada-Nya adalah dosa besar terhadap Keilahian-Nya yang Maha Sempurna.\n\nKarena manusia adalah makhluk terbatas, dan ia dengan keterbatasan bawaannya tidak dapat memahami dengan benar sesuatu yang tidak dikenalnya, tetapi melalui beberapa contoh dalam istilah yang digunakan untuk hal-hal fisik, beberapa istilah harus digunakan secara tidak terhindarkan, sebaliknya esensi atau sifat-sifat Tuhan tidak dapat dijelaskan atau didefinisikan dengan apa pun dari pengetahuan manusia, bahkan dengan kaya raya ekspresi linguistik yang dapat diciptakan oleh manusia dari tambang pikirannya. Segala sesuatu yang diciptakan manusia akan jauh lebih tidak relevan, tidak mungkin, dan sangat tidak memadai untuk menghadapi masalah yang berkaitan dengan pengetahuan tentang Yang Tak Terbatas.",-0.232454,qwen3-8b,minimal
16,"Be the evil doers, the Jinns or human beings. It is a well-known fact that among the forces hidden from the human eye, which are active in the world, there are good and also bad ones among them. Jinns, like Satan are spiritual beings<{[""F"", 1]}>.\n\n**The End**","Jadi menjadi pelaku kejahatan, Jinns atau manusia. Ini adalah fakta yang sudah dikenal bahwa di antara kekuatan-kekuatan yang tersembunyi dari mata manusia, yang aktif di dunia ini, terdapat yang baik dan juga yang buruk di antaranya. Jinns, seperti Iblis, adalah makhluk spiritual<{[""F"", 1]}>.\n\n**Akhir**",-0.230207,qwen3-8b,professional
153,"The root of '_Hutama'_ is '_Hatima'_, i.e., getting rendered or broken into pieces, i.e., it will be crushed, destroyed and thrown into Hell before the eyes of those who spent their lives in amassing it and prided over it and got intoxicated of it, thinking it to be of a permanent value to them - deprived the others of their share, did not spend of it for the benefit of the others who suffered miserably for want of something of it. Besides they had been so much maddened by the acquisition of their wealth they had forgotten God who had allowed them to have it, and thought themselves totally independent of Him and acted as their devilish passions dictated to them, never cared for the limits prescribed by the Lord.\n\n'_Hutama'_ that which will break or destroy it, is the Hell-fire.","Akar dari '_Hutama_' adalah '_Hatima_', yaitu proses menjadi terkena dampak atau hancur berkeping-keping, yaitu akan dihancurkan, dihancurkan, dan dilempar ke Neraka di hadapan orang-orang yang menghabiskan hidup mereka untuk mengumpulkan dan membanggakan diri atasnya serta terlena olehnya, menganggapnya memiliki nilai yang kekal bagi mereka, mengambil bagian orang lain, tidak menghabiskan untuk kebaikan orang lain yang menderita secara menderita karena kekurangan sesuatu dari itu. Selain itu, mereka terlalu terpukau oleh pengumpulan kekayaan mereka hingga lupa akan Tuhan yang telah memberikan kekayaan itu kepada mereka, dan menganggap diri mereka benar-benar mandiri dari-Nya serta bertindak sesuai dengan hasrat iblis yang mengendalikan mereka, tidak pernah memperhatikan batas-batas yang ditetapkan oleh Tuhan.\n\n'_Hutama_' yang akan memecah atau menghancurkannya adalah api Neraka.",-0.227052,qwen3-8b,minimal